### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by Royalton** [Pithus/bazaar#147]
in requirements/build.txt there is a line dexofuzzy==1.7.1  version 1.7.1 as of Jan 1st is no longer available via pip install and is now 2.0.0.

**Comment by aasim-akhtar** [comment]
Facing same issue

```
39.47   Preparing metadata (setup.py): started
46.65   Preparing metadata (setup.py): finished with status 'done'
47.01 Collecting google-play-scraper==1.2.2 (from -r /requirements/base.txt (line 33))
47.12   Downloading google_play_scraper-1.2.2-py3-none-any.whl (28 kB)
47.47 Collecting gpapi==0.4.4 (from -r /requirements/base.txt (line 34))
47.85   Downloading gpapi-0.4.4-py3-none-any.whl (103 kB)
47.90      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.7/103.7 kB 2.7 MB/s eta 0:00:00
48.06 Collecting requests==2.28.1 (from -r /requirements/base.txt (line 35))
48.25   Downloading requests-2.28.1-py3-none-any.whl (62 kB)
48.27      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 3.2 MB/s eta 0:00:00
48.61 ERROR: Ignored the following versions that require a different python version: 4.0.2 Requires-Python >=3.9,<4.0; 5.0 Requires-Python >=3.10; 5.0.1 Requires-Python >=3.10; 5.0.2 Requires-Python >=3.10; 5.0a1 Requires-Python >=3.10; 5.0b1 Requires-Python >=3.10; 5.0rc1 Requires-Python >=3.10
48.61 ERROR: Could not find a version that satisfies the requirement dexofuzzy==1.7.1 (from versions: 2.0.0)
48.61 ERROR: No matching distribution found for dexofuzzy==1.7.1
------
failed to solve: process "/bin/sh -c pip install -r /requirements/local.txt" did not complete successfully: exit code: 1
```

Also when I changed to  `dexofuzzy 2.0.0` I encountered another issue in `django allauth` dependency.


```=> [django internal] load build context                                                                              0.0s
 => => transferring context: 2.31kB                                                                                   0.0s
 => CACHED [worker  2/16] RUN apt-get update   && apt-get install -y build-essential   && apt-get install -y libpq-d  0.0s
 => [django  3/16] COPY ./requirements /requirements                                                                  1.2s
 => [django  4/16] RUN pip install --upgrade pip                                                                      3.9s
 => ERROR [django  5/16] RUN pip install -r /requirements/local.txt                                                 143.9s
------
 > [django  5/16] RUN pip install -r /requirements/local.txt:
0.710 Collecting git+https://github.com/U039b/AndroCFG.git (from -r /requirements/base.txt (line 37))
0.711   Cloning https://github.com/U039b/AndroCFG.git to /tmp/pip-req-build-sauk3gvu
0.716   Running command git clone --filter=blob:none --quiet https://github.com/U039b/AndroCFG.git /tmp/pip-req-build-sauk3gvu
2.841   Resolved https://github.com/U039b/AndroCFG.git to commit 7cc13b63bca0d672ec45b924d9ec937b06293cab
2.847   Preparing metadata (setup.py): started
3.196   Preparing metadata (setup.py): finished with status 'done'
3.374 Collecting pytz==2020.4 (from -r /requirements/base.txt (line 1))
3.487   Downloading pytz-2020.4-py2.py3-none-any.whl (509 kB)
3.628      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 509.0/509.0 kB 3.7 MB/s eta 0:00:00
3.681 Collecting python-slugify==4.0.1 (from -r /requirements/base.txt (line 2))
3.724   Downloading python-slugify-4.0.1.tar.gz (11 kB)
3.730   Preparing metadata (setup.py): started
4.275   Preparing metadata (setup.py): finished with status 'done'
4.494 Collecting Pillow==8.0.1 (from -r /requirements/base.txt (line 3))
4.551   Downloading Pillow-8.0.1-cp38-cp38-manylinux2014_aarch64.whl (2.1 MB)
4.845      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 7.3 MB/s eta 0:00:00
5.204 Collecting rcssmin==1.0.6 (from -r /requirements/base.txt (line 4))
5.297   Downloading rcssmin-1.0.6.tar.gz (582 kB)
5.414      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 582.9/582.9 kB 5.1 MB/s eta 0:00:00
5.468   Preparing metadata (setup.py): started
5.853   Preparing metadata (setup.py): finished with status 'done'
5.912 Collecting argon2-cffi==20.1.0 (from -r /requirements/base.txt (line 5))
5.953   Downloading argon2-cffi-20.1.0.tar.gz (1.8 MB)
7.781      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 989.6 kB/s eta 0:00:00
7.845   Installing build dependencies: started
21.16   Installing build dependencies: finished with status 'done'
21.17   Getting requirements to build wheel: started
21.45   Getting requirements to build wheel: finished with status 'done'
21.45   Preparing metadata (pyproject.toml): started
21.84   Preparing metadata (pyproject.toml): finished with status 'done'
21.89 Collecting whitenoise==5.2.0 (from -r /requirements/base.txt (line 6))
21.92   Downloading whitenoise-5.2.0-py2.py3-none-any.whl (19 kB)
22.10 Collecting redis==3.5.3 (from -r /requirements/base.txt (line 7))
22.13   Downloading redis-3.5.3-py2.py3-none-any.whl (72 kB)
22.61      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.1/72.1 kB 163.2 kB/s eta 0:00:00
22.77 Collecting hiredis==1.1.0 (from -r /requirements/base.txt (line 8))
22.80   Downloading hiredis-1.1.0.tar.gz (54 kB)
23.18      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.6/54.6 kB 214.8 kB/s eta 0:00:00
23.19   Preparing metadata (setup.py): started
23.55   Preparing metadata (setup.py): finished with status 'done'
23.60 Collecting uvicorn==0.12.2 (from uvicorn[standard]==0.12.2->-r /requirements/base.txt (line 9))
23.63   Downloading uvicorn-0.12.2-py3-none-any.whl (45 kB)
23.78      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.1/45.1 kB 360.1 kB/s eta 0:00:00
23.89 Collecting django==3.2.4 (from -r /requirements/base.txt (line 13))
23.92   Downloading Django-3.2.4-py3-none-any.whl (7.9 MB)
38.41      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 545.0 kB/s eta 0:00:00
40.56 Collecting django-environ==0.4.5 (from -r /requirements/base.txt (line 14))
40.59   Downloading django_environ-0.4.5-py2.py3-none-any.whl (21 kB)
44.97 Collecting django-model-utils==4.0.0 (from -r /requirements/base.txt (line 15))
45.00   Downloading django_model_utils-4.0.0-py2.py3-none-any.whl (29 kB)
45.65 Collecting django-allauth==0.44.0 (from -r /requirements/base.txt (line 16))
45.69   Downloading django-allauth-0.44.0.tar.gz (572 kB)
46.01      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.5/572.5 kB 1.8 MB/s eta 0:00:00
46.18   Preparing metadata (setup.py): started
55.32   Preparing metadata (setup.py): finished with status 'error'
55.34   error: subprocess-exited-with-error
55.34
55.34   × python setup.py egg_info did not run successfully.
55.34   │ exit code: 1
55.34   ╰─> [3 lines of output]
55.34       running egg_info
55.34       creating /tmp/pip-pip-egg-info-pm984ldw/django_allauth.egg-info
55.34       error: could not create '/tmp/pip-pip-egg-info-pm984ldw/django_allauth.egg-info': Read-only file system
55.34       [end of output]
55.34
55.34   note: This error originates from a subprocess, and is likely not a problem with pip.
55.35 error: metadata-generation-failed
55.35
55.35 × Encountered error while generating package metadata.
55.35 ╰─> See above for output.
55.35
55.35 note: This is an issue with the package mentioned above, not pip.
55.35 hint: See above for details.
58.40 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-build-tracker-5s46uqy2'.
58.40 You can safely remove it manually.
61.43 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-pip-egg-info-pm984ldw'.
61.43 You can safely remove it manually.
64.46 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-unpack-ou1rmtap'.
64.46 You can safely remove it manually.
67.63 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-install-i1vd_0hv/django-allauth_46a68c22dadc465daf96349ac5bd1c39'.
67.63 You can safely remove it manually.
70.66 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-unpack-t3e1mnxq'.
70.66 You can safely remove it manually.
73.68 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-unpack-bvtm6i97'.
73.68 You can safely remove it manually.
76.71 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-unpack-0yju7v2t'.
76.71 You can safely remove it manually.
79.74 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-unpack-q5xczcz8'.
79.74 You can safely remove it manually.
82.77 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-pip-egg-info-ygpkhtat'.
82.77 You can safely remove it manually.
85.81 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-unpack-eym69yj1'.
85.81 You can safely remove it manually.
88.85 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-install-i1vd_0hv/hiredis_6cd5b8955e134bd9a5f48c795cc0957c'.
88.85 You can safely remove it manually.
91.88 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-unpack-9s_8evjs'.
91.88 You can safely remove it manually.
94.90 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-unpack-xok_lmdb'.
94.90 You can safely remove it manually.
97.95 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-modern-metadata-feqkbbql'.
97.95 You can safely remove it manually.
101.1 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-build-env-2ed6tkch'.
101.1 You can safely remove it manually.
104.1 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-unpack-f4ir0n5k'.
104.1 You can safely remove it manually.
107.2 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-install-i1vd_0hv/argon2-cffi_b7d62804db6847568bb13f6ccb7e5be3'.
107.2 You can safely remove it manually.
110.2 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-pip-egg-info-aigm276f'.
110.2 You can safely remove it manually.
113.2 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-unpack-piyy5bks'.
113.2 You can safely remove it manually.
116.3 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-install-i1vd_0hv/rcssmin_95b9e1e0c2e34568bdd9e03b1c87b190'.
116.3 You can safely remove it manually.
119.4 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-unpack-yfo3w4pc'.
119.4 You can safely remove it manually.
122.4 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-pip-egg-info-s36ozb14'.
122.4 You can safely remove it manually.
125.4 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-unpack-q4j_5rss'.
125.4 You can safely remove it manually.
128.4 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-install-i1vd_0hv/python-slugify_2af99b0b0d7d4866b94f98bb88026038'.
128.4 You can safely remove it manually.
131.5 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-unpack-z5goceo8'.
131.5 You can safely remove it manually.
134.5 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-pip-egg-info-ep4jjyro'.
134.5 You can safely remove it manually.
137.6 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-req-build-sauk3gvu'.
137.6 You can safely remove it manually.
140.6 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-ephem-wheel-cache-8m10hgpq'.
140.6 You can safely remove it manually.
143.8 WARNING: Failed to remove contents in a temporary directory '/tmp/pip-install-i1vd_0hv'.
143.8 You can safely remove it manually.
143.8 Traceback (most recent call last):
143.8   File "/usr/local/bin/pip", line 8, in <module>
143.8     sys.exit(main())
143.8   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 79, in main
143.8     return command.main(cmd_args)
143.8   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 101, in main
143.8     return self._main(args)
143.8   File "/usr/local/lib/python3.8/contextlib.py", line 120, in __exit__
143.8     next(self.gen)
143.8   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/command_context.py", line 20, in main_context
143.8     yield
143.8   File "/usr/local/lib/python3.8/contextlib.py", line 525, in __exit__
143.8     raise exc_details[1]
143.8   File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
143.8     self.gen.throw(type, value, traceback)
143.8   File "/usr/local/lib/python3.8/site-packages/pip/_internal/utils/temp_dir.py", line 81, in tempdir_registry
143.8     yield _tempdir_registry
143.8   File "/usr/local/lib/python3.8/contextlib.py", line 510, in __exit__
143.8     if cb(*exc_details):
143.8   File "/usr/local/lib/python3.8/contextlib.py", line 120, in __exit__
143.8     next(self.gen)
143.8   File "/usr/local/lib/python3.8/site-packages/pip/_internal/operations/build/build_tracker.py", line 51, in get_build_tracker
143.8     yield tracker
143.8   File "/usr/local/lib/python3.8/site-packages/pip/_internal/operations/build/build_tracker.py", line 82, in __exit__
143.8     self.cleanup()
143.8   File "/usr/local/lib/python3.8/site-packages/pip/_internal/operations/build/build_tracker.py", line 126, in cleanup
143.8     self.remove(req, key)
143.8   File "/usr/local/lib/python3.8/site-packages/pip/_internal/operations/build/build_tracker.py", line 119, in remove
143.8     os.unlink(self._entry_path(key))
143.8 OSError: [Errno 30] Read-only file system: '/tmp/pip-build-tracker-5s46uqy2/4a486643750e152505a77f562f3fc1e3515864b406761ce55d42fcfc'
------
failed to solve: error committing xdlgiiibzwhjjhb8lyq1kldgp: read-only file system
```

**Comment by trpyn** [comment]
fixed in a0d2fb5be487d7d76074456a0206c0e0ea9ec1f3
