### ISSUE TITLE
Unable to unzip files with too long names

### ISSUE THREAD

**Issue by U039b** [Pithus/bazaar#28]
```
x@pithus ~/bazaar # docker-compose -f production.yml run --rm django python manage.py update_reports "126a2cab78aca9c78be086eb6d1e363c6927129d62f12b49ae0c15b89107a28c" mbfascqyv
Creating bazaar_django_run ... done
PostgreSQL is available
/usr/local/lib/python3.8/site-packages/django_q/conf.py:136: UserWarning: Retry and timeout are misconfigured. Set retry larger than timeout, 
        failure to do so will cause the tasks to be retriggered before completion. 
        See https://django-q.readthedocs.io/en/latest/configure.html#retry for details.
  warn("""Retry and timeout are misconfigured. Set retry larger than timeout,
WARNING 2021-06-06 17:25:37,451 base 1 140546873874240 PUT http://elasticsearch:9200/google_play_details [status:400 request:0.003s]
RequestError(400, 'resource_already_exists_exception', 'index [google_play_details/hjyogKnWRzeSavwVbcUa5g] already exists')
WARNING 2021-06-06 17:25:37,453 base 1 140546873874240 PUT http://elasticsearch:9200/dexofuzzy_apk [status:400 request:0.002s]
RequestError(400, 'resource_already_exists_exception', 'index [dexofuzzy_apk/LBmeN4QNTuG9zzSNICS2aQ] already exists')
Start mobsf_analysis for 126a2cab78aca9c78be086eb6d1e363c6927129d62f12b49ae0c15b89107a28c
17:25:38 [Q] INFO Enqueued 1
Start malware_bazaar_analysis for 126a2cab78aca9c78be086eb6d1e363c6927129d62f12b49ae0c15b89107a28c
Start frosting_analysis for 126a2cab78aca9c78be086eb6d1e363c6927129d62f12b49ae0c15b89107a28c
Start vt_analysis for 126a2cab78aca9c78be086eb6d1e363c6927129d62f12b49ae0c15b89107a28c
Start apkid_analysis for 126a2cab78aca9c78be086eb6d1e363c6927129d62f12b49ae0c15b89107a28c
17:25:54 [Q] INFO Enqueued 1
Start ssdeep_analysis for 126a2cab78aca9c78be086eb6d1e363c6927129d62f12b49ae0c15b89107a28c
ERROR 2021-06-06 17:25:54,944 update_reports 1 140546873874240 [Errno 36] File name too long: '/tmp/tmpj6200kcx/META-INF/services/o0ooo0O0o0Oo0OOoO000o0oOO0O000O0OOOo.OooOoO0O0oooooo0OO0ooOOooooo00O00OO0.O0000Oo0oOOO0oooooooo0OO00o0OoO0oOOO.oOoo00OOOoOOOo00O0oO00o0ooOOoooooooO.oOoooOo0OOOoOOOo000O0oo0OO0OOo0OOO0o.oo0O0oOoOOoOoOoOOo0o0o0OOOoo000oOOo0.oOoo00OOOoOOOo00O0oO00o0ooOOoooooooO'
Traceback (most recent call last):
  File "/app/bazaar/core/management/commands/update_reports.py", line 46, in _handle_sample
    ssdeep_analysis(sha256)
  File "/app/bazaar/core/tasks.py", line 404, in ssdeep_analysis
    apk.extractall(tmp_dir)
  File "/usr/local/lib/python3.8/zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/local/lib/python3.8/zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
OSError: [Errno 36] File name too long: '/tmp/tmpj6200kcx/META-INF/services/o0ooo0O0o0Oo0OOoO000o0oOO0O000O0OOOo.OooOoO0O0oooooo0OO0ooOOooooo00O00OO0.O0000Oo0oOOO0oooooooo0OO00o0OoO0oOOO.oOoo00OOOoOOOo00O0oO00o0ooOOoooooooO.oOoooOo0OOOoOOOo000O0oo0OO0OOo0OOO0o.oo0O0oOoOOoOoOoOOo0o0o0OOOoo000oOOo0.oOoo00OOOoOOOo00O0oO00o0ooOOoooooooO'
[ERROR   ] root: [Errno 36] File name too long: '/tmp/tmpj6200kcx/META-INF/services/o0ooo0O0o0Oo0OOoO000o0oOO0O000O0OOOo.OooOoO0O0oooooo0OO0ooOOooooo00O00OO0.O0000Oo0oOOO0oooooooo0OO00o0OoO0oOOO.oOoo00OOOoOOOo00O0oO00o0ooOOoooooooO.oOoooOo0OOOoOOOo000O0oo0OO0OOo0OOO0o.oo0O0oOoOOoOoOoOOo0o0o0OOOoo000oOOo0.oOoo00OOOoOOOo00O0oO00o0ooOOoooooooO'
Traceback (most recent call last):
  File "/app/bazaar/core/management/commands/update_reports.py", line 46, in _handle_sample
    ssdeep_analysis(sha256)
  File "/app/bazaar/core/tasks.py", line 404, in ssdeep_analysis
    apk.extractall(tmp_dir)
  File "/usr/local/lib/python3.8/zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/local/lib/python3.8/zipfile.py", line 1701, in _extract_member
    open(targetpath, "wb") as target:
OSError: [Errno 36] File name too long: '/tmp/tmpj6200kcx/META-INF/services/o0ooo0O0o0Oo0OOoO000o0oOO0O000O0OOOo.OooOoO0O0oooooo0OO0ooOOooooo00O00OO0.O0000Oo0oOOO0oooooooo0OO00o0OoO0oOOO.oOoo00OOOoOOOo00O0oO00o0ooOOoooooooO.oOoooOo0OOOoOOOo000O0oo0OO0OOo0OOO0o.oo0O0oOoOOoOoOoOOo0o0o0OOOoo000oOOo0.oOoo00OOOoOOOo00O0oO00o0ooOOoooooooO'
```

**Comment by alex-bender** [comment]
can you provide that 126a2cab78aca9c78be086eb6d1e363c6927129d62f12b49ae0c15b89107a28c file?

**Comment by U039b** [comment]
GitHub does not support APK file so you should download the sample directly from Pithus https://beta.pithus.org/report/126a2cab78aca9c78be086eb6d1e363c6927129d62f12b49ae0c15b89107a28c.

**Comment by alex-bender** [comment]
done! will take a look

**Comment by alex-bender** [comment]
So in this case the file name of zipped file is more in length than 255, so it is not possible to create such file.
I can propose to trim names to be up to 255 chars, but I'm not sure that this solution will work.
Any thoughts?

**Comment by alex-bender** [comment]
Another question:
Looking at the ssdeep_analysis function I can see that only dex files are being analyzed, plus Manifest and resources.
Is it really needed to extract all the files in such case?

**Comment by U039b** [comment]
> So in this case the file name of zipped file is more in length than 255, so it is not possible to create such file.
> I can propose to trim names to be up to 255 chars, but I'm not sure that this solution will work.

It is safe to trim names.

> Looking at the ssdeep_analysis function I can see that only dex files are being analyzed, plus Manifest and resources.
> Is it really needed to extract all the files in such case?

For sure, it is not necessary to extract all files in that case.

**Comment by alex-bender** [comment]
Thant's great. Then I will implement changes and create a PR
