### ISSUE TITLE
Worker desync issue

### ISSUE THREAD

**Issue by U039b** [Pithus/bazaar#30]
``` 
worker_1         | 15:59:06 [Q] ERROR Failed [whiskey-three-quiet-football] - lost synchronization with server: got message type "5", length 1714972005
worker_1         |  : Traceback (most recent call last):
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
worker_1         |     return self.cursor.execute(sql, params)
worker_1         | psycopg2.OperationalError: lost synchronization with server: got message type "5", length 1714972005
worker_1         | 
worker_1         | 
worker_1         | The above exception was the direct cause of the following exception:
worker_1         | 
worker_1         | Traceback (most recent call last):
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django_q/cluster.py", line 436, in worker
worker_1         |     res = f(*task["args"], **task["kwargs"])
worker_1         |   File "/app/bazaar/core/tasks.py", line 195, in yara_analysis
worker_1         |     for rule in Yara.objects.all():
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 276, in __iter__
worker_1         |     self._fetch_all()
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1261, in _fetch_all
worker_1         |     self._result_cache = list(self._iterable_class(self))
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 57, in __iter__
worker_1         |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
worker_1         |     cursor.execute(sql, params)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 489, in execute
worker_1         |     return real_execute(self, sql, params)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
worker_1         |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
worker_1         |     return executor(sql, params, many, context)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
worker_1         |     return self.cursor.execute(sql, params)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
worker_1         |     raise dj_exc_value.with_traceback(traceback) from exc_value
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
worker_1         |     return self.cursor.execute(sql, params)
worker_1         | django.db.utils.OperationalError: lost synchronization with server: got message type "5", length 1714972005
worker_1         | 
worker_1         | 
worker_1         | 16:01:08 [Q] INFO Process-1:433 stopped doing work
worker_1         | 16:01:08 [Q] INFO Processed [avocado-april-sixteen-michigan]
worker_1         | 16:01:47 [Q] INFO Process-1:413 stopped doing work
worker_1         | 16:01:47 [Q] INFO Processed [nineteen-cold-maine-berlin]
worker_1         | 16:01:54 [Q] INFO Process-1:423 stopped doing work
worker_1         | 16:01:54 [Q] INFO Processed [ceiling-fifteen-don-helium]
worker_1         | PostgreSQL is available
worker_1         | /usr/local/lib/python3.8/site-packages/django_q/conf.py:136: UserWarning: Retry and timeout are misconfigured. Set retry larger than timeout, 
worker_1         |         failure to do so will cause the tasks to be retriggered before completion. 
worker_1         |         See https://django-q.readthedocs.io/en/latest/configure.html#retry for details.
worker_1         |   warn("""Retry and timeout are misconfigured. Set retry larger than timeout,
```

**Comment by U039b** [comment]
```
worker_1         | 10:37:54 [Q] ERROR Failed [tennis-freddie-december-solar] - server closed the connection unexpectedly
worker_1         | 	This probably means the server terminated abnormally
worker_1         | 	before or while processing the request.
worker_1         |  : Traceback (most recent call last):
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 172, in __get__
worker_1         |     rel_obj = self.field.get_cached_value(instance)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/mixins.py", line 13, in get_cached_value
worker_1         |     return instance._state.fields_cache[cache_name]
worker_1         | KeyError: 'owner'
worker_1         | 
worker_1         | During handling of the above exception, another exception occurred:
worker_1         | 
worker_1         | Traceback (most recent call last):
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
worker_1         |     return self.cursor.execute(sql, params)
worker_1         | psycopg2.OperationalError: server closed the connection unexpectedly
worker_1         | 	This probably means the server terminated abnormally
worker_1         | 	before or while processing the request.
worker_1         | 
worker_1         | 
worker_1         | The above exception was the direct cause of the following exception:
worker_1         | 
worker_1         | Traceback (most recent call last):
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django_q/cluster.py", line 436, in worker
worker_1         |     res = f(*task["args"], **task["kwargs"])
worker_1         |   File "/app/bazaar/core/tasks.py", line 196, in yara_analysis
worker_1         |     execute_single_yara_rule(rule, sha256)
worker_1         |   File "/app/bazaar/core/tasks.py", line 119, in execute_single_yara_rule
worker_1         |     es_index = rule.get_es_index_name()
worker_1         |   File "/app/bazaar/core/models.py", line 37, in get_es_index_name
worker_1         |     public_es_index, private_es_index = Yara.get_es_index_names(self.owner)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 186, in __get__
worker_1         |     rel_obj = self.get_object(instance)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 153, in get_object
worker_1         |     return qs.get(self.field.get_reverse_related_filter(instance))
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 411, in get
worker_1         |     num = len(clone)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 258, in __len__
worker_1         |     self._fetch_all()
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1261, in _fetch_all
worker_1         |     self._result_cache = list(self._iterable_class(self))
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 57, in __iter__
worker_1         |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
worker_1         |     cursor.execute(sql, params)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 489, in execute
worker_1         |     return real_execute(self, sql, params)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
worker_1         |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
worker_1         |     return executor(sql, params, many, context)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
worker_1         |     return self.cursor.execute(sql, params)
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
worker_1         |     raise dj_exc_value.with_traceback(traceback) from exc_value
worker_1         |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
worker_1         |     return self.cursor.execute(sql, params)
worker_1         | django.db.utils.OperationalError: server closed the connection unexpectedly
worker_1         | 	This probably means the server terminated abnormally
worker_1         | 	before or while processing the request.
worker_1         | 
worker_1         | 

```

**Comment by U039b** [comment]
Seems to be fixed
